databases:
  - name: crm_db_onwi  # Match the actual database name
    databaseName: crm_db_onwi
    user: crm_db_onwi_user  # Match the actual user
    password: pA6ns0ixJcatYMGQ5DJ5Sks2vyBO1HKl  # Match the actual password (optional, Render overrides)
    plan: free
services:
  - type: web
    name: fastapi-crm-system
    env: python
    buildCommand: "pip install -r requirements.txt && python app/init_db.py"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromRender: true
      - key: SECRET_KEY
        value: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
    repo: https://github.com/Tihetna1891/FastAPICRMSystem